<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="BussinessLogicLayer\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Practices.EnterpriseLibrary.Common">
      <HintPath>..\..\..\Desktop\COBIJA\SIGRH3\SIGRH\Bin\Microsoft.Practices.EnterpriseLibrary.Common.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Practices.EnterpriseLibrary.Configuration.Design">
      <HintPath>..\..\..\Desktop\COBIJA\SIGRH3\SIGRH\Bin\Microsoft.Practices.EnterpriseLibrary.Configuration.Design.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Practices.EnterpriseLibrary.Data">
      <HintPath>..\SIGRH\Bin\Microsoft.Practices.EnterpriseLibrary.Data.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Practices.EnterpriseLibrary.Data.Configuration.Design">
      <HintPath>..\..\..\Desktop\COBIJA\SIGRH3\SIGRH\Bin\Microsoft.Practices.EnterpriseLibrary.Data.Configuration.Design.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Practices.ObjectBuilder">
      <HintPath>..\..\..\Desktop\COBIJA\SIGRH3\SIGRH\Bin\Microsoft.Practices.ObjectBuilder.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
