<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPageSIGRH.master" AutoEventWireup="true" CodeFile="Categorias.aspx.cs" Inherits="Administración_Categorias" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div class="header pb-6" style="margin-top:-4em; margin-left:3em;width:81%"> 
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-light d-inline-block mb-0">Estructura Organizacional</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid mt--6">
        <div class="row">
            <div class="col-lg-5" data-select2-id="9">
                <div class="card mb-4 ">
                    <!-- Card header -->
                    <div class="card-header">
                        <div class=" ct-page-title">
                            <h3 class="mb-0">Estructura Organizacional</h3>
                            <p class="text-sm mb-0">
                                Haga click en la Unidad Organizacional para añadir una nueva dependencia o pulse el Botón NUEVO para crear un nodo padre
                            </p>
                            <asp:LinkButton ID="btnNuevoNodo" CssClass="btn btn-default btn-round btn-icon" data-toggle="tooltip" data-original-title="Nuevo Nodo Padre" OnClick="btnNuevoNodo_Click" Text="<span class='btn-inner--icon'><i class='fas fa-users-cog'></i></span><span class='btn-inner--text'>Nuevo</span>"  runat="server" />
                        </div>
                    </div>

                    <div class="card-body scroll-static-prs">
                        <asp:updatepanel runat="server">
                            <ContentTemplate>

                                <asp:TreeView runat="server" ID="tv_nivelOrg" ImageSet="Arrows" CssClass="treeView" AutoGenerateDataBindings="true" OnSelectedNodeChanged="tv_nivelOrg_SelectedNodeChanged">
                                    <NodeStyle Font-Size=".875em" ForeColor="#525f7f" HorizontalPadding="2px" NodeSpacing="0px" VerticalPadding="2px"></NodeStyle>
                                    <SelectedNodeStyle CssClass="SelectedNodeTreeView" />
                                    <HoverNodeStyle CssClass="HoverTreeView" />
                                </asp:TreeView>
                                <hr />
                            <asp:LinkButton ID="btnEditar" Enabled="false" CssClass="btn btn-info btn-round btn-icon" data-toggle="tooltip" data-original-title="Editar el Nombre de la Unidad Organizacional" OnClick="btnEditar_Click" Text="<span class='btn-inner--icon'><i class='fas fa-edit'></i></span><span class='btn-inner--text'>Editar</span>"  runat="server" />
                            </ContentTemplate>
                            <Triggers> <asp:AsyncPostBackTrigger ControlID="btnNuevoNodo" EventName="Click" />
                            </Triggers>
                        </asp:updatepanel>
                    </div>
                </div>
                    </div>            
            <div class="col-5">
                    <div class="card mb-4">
                        <div class="card-header d-flex align-items-center">
                            <div class="d-flex align-items-center ct-page-title">
                                <div class="text-dark font-weight-600 text-sm">
                             <h3 class="mb-0">Dependencia</h3>
                            <p class="text-sm mb-0">
                                Registre el nodo dependiente para:
                            </p>
                            <p class="text-sm mb-0 text-red bold">
                                Para creación de Nodo Dependiente para Consultoría, deberá colocar al final del nombre, un espacio y (E) o (eventual)
                            </p>
                            </div>
                            </div>  
                            </div>
                        <asp:UpdatePanel runat="server">
                            <ContentTemplate>
                                 <div class="card-body scroll-static-prs">
                                <asp:Label Text="" BackColor="LightGreen" runat="server" class="form-control-label"  ID="lblNodo"  />
                                <div class="input-group input-group-merge">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="fas fa-edit"></i>
                                        </span>
                                    </div>
                                   <asp:TextBox ID="txt_nodo_descripcion" CssClass="form-control" runat="server" />
                                </div>
                                    <asp:RequiredFieldValidator CssClass="text-danger display-5" ErrorMessage="(*) Campo Obligatorio" ControlToValidate="txt_nodo_descripcion" ValidationGroup="dependencia" Display="Dynamic" runat="server" />
                           <!-- tipo -->
                           <div class="card-body scroll-static-prs" style="top:-2em">
<%--                            <div class="form-group col-md-6">--%>
<%--                                <label class="form-control-label" for="rblTipo">Tipo</label>--%>
<%--                                <div class="custom-control custom-radio" >
                                    <asp:RadioButtonList ID="rblTipo" CssClass="radios" RepeatDirection="Horizontal" runat="server">
                                        <asp:ListItem Value="C" Text="Contrato" />
                                        <asp:ListItem Value="E1" Text="Consultoría" />
                                    </asp:RadioButtonList>
                                </div>--%>
<%--                                <asp:RequiredFieldValidator CssClass="text-danger display-5" ErrorMessage="(*) Campo Obligatorio" ControlToValidate="rblTipo" ValidationGroup="dependencia" Display="Dynamic" runat="server" />--%>
<%--                            </div>--%>
                        <div class="form-group col-md-12">
                           <asp:LinkButton ID="btnRegistrarDependencia" CssClass="btn btn-success" Text="<i class='fas fa-save'></i> Registrar" ValidationGroup="dependencia" OnClick="BtnGuardarF_Click" runat="server"  />
                           <asp:LinkButton ID="btnEliminar" CssClass="btn btn-warning" Text="<i class='fas fa-delete'></i>Eliminar" ValidationGroup="family"  OnClick="btnEliminar_Click" runat="server" />
                           <asp:LinkButton ID="btnCancelarDependencia" CssClass="btn btn-google-plus" Text="<i class='fas fa-times'></i> Cancelar"  OnClick="btnCancelarDependencia_Click" runat="server" />
                       </div>
                            </div>
                        <asp:UpdatePanel runat="server">
                            <ContentTemplate>
                        <div class="card-body scroll-static-prs">
                        <div class="card-header d-flex align-items-center">
                            <div class="d-flex align-items-center ct-page-title">
                                <div class="text-dark font-weight-600 text-sm">
                                        <h3 class="mb-0">Categoría Programática</h3>
                                        <p class="text-sm mb-0">
                                            Seleccione la Categoría Programática para la Unidad Organizacional seleccionada o pulse el botón NUEVA CATEGORIA para crear una
                                        </p>
                                <asp:LinkButton ID="btnNuevaCategoria" CssClass="btn btn-default btn-round btn-icon" data-toggle="tooltip"  OnClick="btnNuevaCategoria_Click" Text="<span class='btn-inner--icon'><i class='fas fa-users-cog'></i></span><span class='btn-inner--text'>Nueva Categoría</span>"  runat="server" />

                                    
                                </div>
                            </div>


                        </div>
                            <asp:DropDownList ID="ddlCategorias" OnSelectedIndexChanged="ddlCategorias_SelectedIndexChanged" AutoPostBack="true" CssClass="form-control select2" AppendDataBoundItems="true" runat="server" />
<%--                            <asp:RequiredFieldValidator CssClass="text-danger display-5" ErrorMessage="(*) Campo Obligatorio" ControlToValidate="ddlCategorias" ValidationGroup="add" InitialValue="0" Display="Dynamic" runat="server" />--%>
                        </div>
                            </ContentTemplate>
                        </asp:UpdatePanel>

                            </div>

                            </ContentTemplate>
                            <Triggers>
                                    <asp:AsyncPostBackTrigger ControlID="btnRegistrarDependencia" EventName="Click" />
                                    <asp:AsyncPostBackTrigger ControlID="btnCancelarDependencia" EventName="Click" />
                                    <asp:AsyncPostBackTrigger ControlID="btnEliminar" EventName="Click" />
                            </Triggers>
                        </asp:UpdatePanel>                      
                </div>

            </div>
         
            </div>

        </div>
    <div id="modalNodo" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="familyTitle" aria-hidden="true" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                        <div class="card-header d-flex align-items-center">
                            <div class="d-flex align-items-center ct-page-title">
                                <div class="text-dark font-weight-600 text-sm">
                             <h3 class="mb-0">Nuevo Nodo PADRE</h3>
                            <p class="text-sm mb-0">
                                Registre el nodo inicial de donde depnderán otras unidades
                            </p>
                            <p class="text-sm mb-0 text-red bold">
                                Para creación de Nodo para Consultoría, deberá colocar al final del nombre, un espacio y (E) o (eventual)
                            </p>
                            </div>
                            </div>  
                            </div>
                        <asp:UpdatePanel runat="server">
                            <ContentTemplate>
                                <div class="card-body scroll-static-prs">
                                <asp:Label Text="" BackColor="LightGreen" runat="server" class="form-control-label"  ID="Label1"  />

                                <div class="input-group input-group-merge">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="fas fa-edit"></i>
                                        </span>
                                    </div>
                                    <asp:TextBox ID="txtNuevoNodo" CssClass="form-control" runat="server" />
                                </div>
                                </div>
                            </ContentTemplate>
                    <Triggers>
                        <asp:AsyncPostBackTrigger ControlID="btnRegistrarNuevoNodo" EventName="Click" />
                        <asp:AsyncPostBackTrigger ControlID="btnCancelarNuevoNodo" EventName="Click" />
                    </Triggers>

                        </asp:UpdatePanel>
                <asp:RequiredFieldValidator CssClass="text-danger display-5" ErrorMessage="(*) Campo Obligatorio" ControlToValidate="txtNuevoNodo" ValidationGroup="adding" Display="Dynamic" runat="server" />
                       <div class="form-group col-md-6">
                           <asp:LinkButton ID="btnRegistrarNuevoNodo" CssClass="btn btn-success" Text="<i class='fas fa-save'></i> Registrar" ValidationGroup="adding" OnClick="btnRegistrarNuevoNodo_Click" runat="server" />
                           <asp:LinkButton ID="btnCancelarNuevoNodo" CssClass="btn btn-google-plus" Text="<i class='fas fa-times'></i> Cancelar"  OnClick="BtnCancelarF_Click" runat="server" />
                       </div>

            </div>
        </div>
    </div>
    <div id="modalCategorias" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="familyTitle" aria-hidden="true" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header border-bottom">
                    <div class="ct-page-title">
                        <h5 id="CategoriasTitle" class="modal-title">Nueva Categoría</h5>
                        <p class="text-sm mb-0"></p>
                    </div>
                </div>
                <asp:UpdatePanel runat="server">
                    <ContentTemplate>
        <div class=" row form-group col-md-12">
            <div class="col-md-3">
            <label class="form-control-label" for="Txt_per_nombres">D.A.</label>
            <asp:TextBox ID="txtDA" CssClass="form-control number" runat="server" />
            <asp:RequiredFieldValidator CssClass="text-danger display-5" ErrorMessage="(*) Campo Obligatorio" ControlToValidate="txtDA" ValidationGroup="categorias" InitialValue="0" Display="Dynamic" runat="server" />
            </div>

            <div class="col-md-9">
            <label class="form-control-label" for="txtDaDescripcion">Descripción D.A.</label>
            <asp:TextBox ID="txtDaDescripcion" CssClass="form-control" runat="server" />
            <asp:RequiredFieldValidator CssClass="text-danger display-5" ErrorMessage="(*) Campo Obligatorio" ControlToValidate="txtDaDescripcion" ValidationGroup="categorias" InitialValue="0" Display="Dynamic" runat="server" />
            </div>
        </div>
        <div class=" row form-group col-md-12">
            <div class="col-md-3">
            <label class="form-control-label" for="txtUE">U.E.</label>
            <asp:TextBox ID="txtUE" CssClass="form-control number" runat="server" />
            <asp:RequiredFieldValidator CssClass="text-danger display-5" ErrorMessage="(*) Campo Obligatorio" ControlToValidate="txtUE" ValidationGroup="categorias" InitialValue="0" Display="Dynamic" runat="server" />
            </div>

            <div class="col-md-9">
            <label class="form-control-label" for="txtDaDescripcion">Descripción U.E.</label>
            <asp:TextBox ID="txtUEDescripcion" CssClass="form-control" runat="server" />
            <asp:RequiredFieldValidator CssClass="text-danger display-5" ErrorMessage="(*) Campo Obligatorio" ControlToValidate="txtUEDescripcion" ValidationGroup="categorias" InitialValue="0" Display="Dynamic" runat="server" />
            </div>
        </div>
        <div class=" row form-group col-md-12">
            <div class="col-md-2">
            <label class="form-control-label" for="txtProg">PROGRAMA:</label>
            <asp:TextBox ID="txtProg" CssClass="form-control number" runat="server" />
            <asp:RequiredFieldValidator CssClass="text-danger display-5" ErrorMessage="(*) Campo Obligatorio" ControlToValidate="txtProg" ValidationGroup="categorias" InitialValue="0" Display="Dynamic" runat="server" />
            </div>

            <div class="col-md-2">
            <label class="form-control-label" for="txtProy">PROYECTO:</label>
            <asp:TextBox ID="txtProy" CssClass="form-control number" runat="server" />
            <asp:RequiredFieldValidator CssClass="text-danger display-5" ErrorMessage="(*) Campo Obligatorio" ControlToValidate="txtProy" ValidationGroup="categorias" InitialValue="0" Display="Dynamic" runat="server" />
            </div>

            <div class="col-md-2">
            <label class="form-control-label" for="txtAct">ACTIVIDAD:</label>
            <asp:TextBox ID="txtAct" CssClass="form-control number" runat="server" />
            <asp:RequiredFieldValidator CssClass="text-danger display-5" ErrorMessage="(*) Campo Obligatorio" ControlToValidate="txtAct" ValidationGroup="categorias" InitialValue="0" Display="Dynamic" runat="server" />
            </div>
        </div>

        <div class="form-group col-md-9">
        <label class="form-control-label" for="Txt_per_nombres">Nombre Categoría</label>
        <asp:TextBox ID="txtCategoria" CssClass="form-control number" runat="server" />
        <asp:RequiredFieldValidator CssClass="text-danger display-5" ErrorMessage="(*) Campo Obligatorio" ControlToValidate="txtCategoria" ValidationGroup="categorias" InitialValue="0" Display="Dynamic" runat="server" />
        </div>
        <div class="row form-group col-md-12">
        <div class="col-md-4">
        <label class="form-control-label" for="Txt_per_nombres">Fuente de Financiamiento</label>
        <asp:TextBox ID="txtFuenteFinanciamiento" CssClass="form-control number" runat="server" />
        <asp:RequiredFieldValidator CssClass="text-danger display-5" ErrorMessage="(*) Campo Obligatorio" ControlToValidate="txtFuenteFinanciamiento" ValidationGroup="categorias" InitialValue="0" Display="Dynamic" runat="server" />
        </div>
        <div class="col-md-3">
        <label class="form-control-label" for="Txt_per_nombres">Organismo</label>
        <asp:TextBox ID="txtOrganismo" CssClass="form-control number" runat="server" />
        <asp:RequiredFieldValidator CssClass="text-danger display-5" ErrorMessage="(*) Campo Obligatorio" ControlToValidate="txtOrganismo" ValidationGroup="categorias" InitialValue="0" Display="Dynamic" runat="server" />
        </div>
        </div>
        <div class="col-md-6">
        <label class="form-control-label" for="Txt_per_nombres">Tipo de Gasto:</label>
                        <asp:DropDownList ID="ddlTipoGasto" runat="server" CssClass="form-control">
                            <asp:ListItem Text="INVERSIÓN" Value="K" />
                            <asp:ListItem Text="CORRIENTE"  Value="C"/>
                        </asp:DropDownList>
        <asp:RequiredFieldValidator CssClass="text-danger display-5" ErrorMessage="(*) Campo Obligatorio" ControlToValidate="ddlTipoGasto" ValidationGroup="categorias" InitialValue="0" Display="Dynamic" runat="server" />

        </div>
        <hr />
        <div class="form-group col-md-6">
                            <asp:LinkButton ID="btnRegstrarCategoria" CssClass="btn btn-success" Text="<i class='fas fa-save'></i> Registrar" ValidationGroup="categorias"  OnClick="btnRegstrarCategoria_Click" runat="server" />
                            <asp:LinkButton ID="btnCancelarCategoria" CssClass="btn btn-google-plus" Text="<i class='fas fa-times'></i> Cancelar"  OnClick="btnCancelarCategoria_Click" runat="server" />
                        </div>
                    </ContentTemplate>
                    <Triggers>
                        <asp:AsyncPostBackTrigger ControlID="btnRegstrarCategoria" EventName="Click" />
                        <asp:AsyncPostBackTrigger ControlID="btnCancelarCategoria" EventName="Click" />
                    </Triggers>
                </asp:UpdatePanel>
            </div>
        </div>
    </div>

    <div id="modalEditarEstructura" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="familyTitle" aria-hidden="true" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                        <asp:UpdatePanel runat="server">
                            <ContentTemplate>

                        <div class="card-header d-flex align-items-center">
                            <div class="d-flex align-items-center ct-page-title">
                                <div class="text-dark font-weight-600 text-sm">
                                    <asp:Label class="mb-0" Text="" ID="lblModificar" runat="server" />
                            <p class="text-sm mb-0">
                                Registre el nuevo nombre de la Unidad Organizacional
                            </p>
                            </div>
                            </div>  
                            </div>
                                <div class="card-body scroll-static-prs">
                                <asp:Label Text="" BackColor="LightGreen" runat="server" class="form-control-label"  ID="Label2"  />

                                <div class="input-group input-group-merge">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="fas fa-edit"></i>
                                        </span>
                                    </div>
                                    <asp:TextBox ID="txtNuevoNombreUnidad" CssClass="form-control" runat="server" />
                                </div>
                                </div>
                            </ContentTemplate>
                    <Triggers>
                        <asp:AsyncPostBackTrigger ControlID="btnRegistrarUnidad" EventName="Click" />
                        <asp:AsyncPostBackTrigger ControlID="btnCancelarUnidad" EventName="Click" />
                    </Triggers>

                        </asp:UpdatePanel>
                <asp:RequiredFieldValidator CssClass="text-danger display-5" ErrorMessage="(*) Campo Obligatorio" ControlToValidate="txtNuevoNombreUnidad" ValidationGroup="addi" Display="Dynamic" runat="server" />
                       <div class="form-group col-md-6">
                           <asp:LinkButton ID="btnRegistrarUnidad" CssClass="btn btn-success" Text="<i class='fas fa-save'></i> Registrar" ValidationGroup="addi"  OnClick="btnRegistrarUnidad_Click"  runat="server" />
                           <asp:LinkButton ID="btnCancelarUnidad" CssClass="btn btn-google-plus" Text="<i class='fas fa-times'></i> Cancelar" OnClick="btnCancelarUnidad_Click"  runat="server" />
                       </div>

            </div>
        </div>
    </div>

</asp:Content>

