<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPageSIGRH.master" AutoEventWireup="true" CodeFile="EstructuraOrganizacional.aspx.cs" Inherits="ManualPuestos_EstructuraOrganizacional" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <div class="header bg-org2 pb-5"style="min-height: 170px; background-image: url(../Content/img/fondo_uap1.png); background-size: cover; background-position: center top;">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-bluedark d-inline-block mb-0">Personal Permanente Administrativos y Docentes Titulares</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid mt--6">

<%--        <div class="row justify-content-center">--%>
            <div class="col-lg-10 card-wrapper ct-example">
                <!-- Styles -->
                <div class="card mb-7 ">
                    <!-- Card header -->
                    <div class="card-header">
                        <div class=" ct-page-title">
                            <h3 class="mb-0">Estructura Organizacional </h3>
                            <p class="text-sm mb-0">
                                Seleccione la Unidad Organizacional requerida o digite el numero de item a buscar.
                            </p>
                        </div>


                    </div>

                    <!-- Card body -->
                    <div class="card-body ">
                        <asp:UpdatePanel runat="server">
                            <ContentTemplate>
                                <asp:Panel DefaultButton="btn_buscar_est_org" runat="server">
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label class="form-control-label">Unidad organizacional</label>
                                                <asp:DropDownList ID="ddl_est_org" CssClass="form-control select2 " AppendDataBoundItems="true" OnSelectedIndexChanged="ddl_est_org_SelectedIndexChanged" AutoPostBack="true" runat="server" />
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="form-control-label">Número de ítem </label>
                                                <asp:TextBox ID="txt_numero_item" CssClass="form-control" type="number" runat="server" />
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="form-control-label">&nbsp</label>
                                                <asp:LinkButton ID="btn_buscar_est_org" CssClass="btn btn-info btn-block" Text="<i class='fas fa-search'></i> Buscar" OnClick="btn_buscar_est_org_Click" runat="server" />
                                            </div>
                                        </div>
                                    </div>
                                    <asp:HiddenField ID="hf_ca_id" runat="server" />
                                </asp:Panel>
                            </ContentTemplate>
                        </asp:UpdatePanel>

                    </div>
                              <div  class="col-md-4">
                                     <div class="text-left md-3" >
                                    <asp:UpdatePanel ID="panelImpresion" runat="server" >
                                        <ContentTemplate>
                                            <asp:LinkButton ID="btn_imprimir" CssClass="btn btn-info btn-block btn-facebook" data-toggle="tooltip" data-original-title="Imprimir" Text="<i class='fas fa-print'></i> GENERAR REPORTE POAI" OnClick="btn_imprimir_Click" runat="server"  />
                                        </ContentTemplate>
                                    </asp:UpdatePanel>
                                 </div>
                             </div>
                    <div class="card-body scroll-static-prs">
                        <asp:UpdatePanel runat="server">
                            <ContentTemplate>

                                <asp:TreeView runat="server" ID="tv_nivelOrg" ImageSet="Arrows" CssClass="treeView" AutoGenerateDataBindings="true" OnSelectedNodeChanged="tv_nivelOrg_SelectedNodeChanged" >
                                    <NodeStyle Font-Size=".875em" ForeColor="#050508" HorizontalPadding="2px" NodeSpacing="0px" VerticalPadding="2px"></NodeStyle>
                                    <SelectedNodeStyle CssClass="SelectedNodeTreeView" />
                                    <HoverNodeStyle CssClass="HoverTreeView" />
                                </asp:TreeView>

                            </ContentTemplate>
                        </asp:UpdatePanel>
                    </div>
                </div>

            </div>
        </div>

<%--    </div>--%>

</asp:Content>

